services:
#    n2_c_user.example:
#        class: N2C\UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    n2c_user.menu:
        class: N2C\UserBundle\Menu\MenuBuilder
        arguments: ['@security.authorization_checker', '@router']
        tags:
            - { name: n2c_core.menu }

