n2_c_media:
    resource: "@N2CMediaBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

n2c_core:
    resource: "@N2CCoreBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

n2c_user:
    resource: "@N2CUserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}



fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
