services:
    n2c_core.menu_builder:
        class: N2C\CoreBundle\Menu\Builder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: getNavbarMenu, alias: n2c.navbar }
